-- 코드를 입력하세요
SELECT II.INGREDIENT_TYPE, SUM(FH.TOTAL_ORDER)
FROM (SELECT INGREDIENT_TYPE, FLAVOR FROM ICECREAM_INFO) II,
     (SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF) FH
WHERE II.FLAVOR = FH.FLAVOR GROUP BY INGREDIENT_TYPE